// siteConfig.ts - 本地管理器使用的博客配置源

export const siteConfig = {
  title: "你的名字 | 次元笔记",
  faviconUrl: "/images/backgrounds/bg-05-cat-girl.webp",
  authorName: "你的名字",
  bio: "在这里写下技术、生活与灵感。",
  navTitle: "YourName",
  navSuffix: "/",
  navAfter: "次元笔记",
  avatarUrl: "/images/backgrounds/bg-05-cat-girl.webp",
  useGradient: false,
  themeColors: ["#0b1220", "#182235", "#ff5a52", "#0b1220"],
  bgImages: [
    "/images/backgrounds/bg-00-bleach.webp",
    "/images/backgrounds/bg-01-columbina.webp",
    "/images/backgrounds/bg-02-reze.webp",
    "/images/backgrounds/bg-03-scenery.webp",
    "/images/backgrounds/bg-04-gargantua.webp",
    "/images/backgrounds/bg-05-cat-girl.webp",
    "/images/backgrounds/bg-06-zoro.webp",
    "/images/backgrounds/bg-07-naruto.webp",
    "/images/backgrounds/bg-08-tanjiro.webp",
    "/images/backgrounds/bg-09-gear-five.webp",
    "/images/backgrounds/bg-10-graffiti.webp",
  ],
  defaultPostCover: "/images/generated/default-post-cover.webp",
  photoWallImage: "/images/backgrounds/bg-02-reze.webp",
  cloudMusicIds: [],
  social: {
    github: "",
    gitee: "",
    google: "",
    email: "",
    qq: "",
    wechat: "",
  },
  counts: {
    photos: 0,
  },
  chatterTitle: "碎片记录",
  chatterDescription: "代码之外的灵感、日常与收藏",
  picBedName: "图床",
  picBedUrl: "",
  picBedToken: "",
  danmakuList: [],
  githubComments: {
    repo: "",
    label: "blog-comment",
  },
  buildDate: "2026-01-01T00:00:00",
  footerBadges: [],
  icpConfig: {
    name: "",
    link: "",
  },
  geminiConfig: {
    modelId: "gemini-2.5-flash-lite",
    systemPrompt: "你是一只简洁、友好的博客助手猫。请使用中文回答，每次不超过 100 字。",
    maxOutputTokens: 150,
    temperature: 0.85,
  },
  friendLinkApplyFormat: "名称：你的博客名称\n简介：一句话介绍你的博客\n链接：https://example.com\n头像：https://example.com/avatar.png",
  enableLevelSystem: false,
};
